org: 46ki75
app: internal
service: internal-backend-pysls-flask

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app

useDotenv: true

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1
  stage: dev
  environment:
    SLS_AWS_ACCESS_KEY_ID: ${env:SLS_AWS_ACCESS_KEY_ID}
    SLS_AWS_SECRET_ACCESS_KEY: ${env:SLS_AWS_SECRET_ACCESS_KEY}
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
  layers:
    - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p310-bcrypt:1
    - arn:aws:lambda:ap-northeast-1:770693421928:layer:Klayers-p310-boto3:1

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
